name: Rust

on:
  push:
    branches: ["feature/implement-github-actions" ]
  pull_request:
    branches: [ "main","develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      env:
        RUSTFLAGS: -Cinstrument-coverage
      run: cargo build --verbose
    - name: Run tests
      env:
        LLVM_PROFILE_FILE: code_coverage-%p-%m.profraw
        RUSTFLAGS: -Cinstrument-coverage
      run: cargo test --verbose
    - name: Generate coverage data
      run: |
        ./target/debug/grcov $(find . -name "grcov-*.profraw" -print) \
          --branch \
          --ignore-not-existing \
          --binary-path ./target/debug/ \
          -s . \
          -t lcov \
          --ignore "/*" \
          -o lcov.info
